edit game_view update and game_piece model
changed game patch request path to accept gameData instead of game as its object to key into. Had difficulty find the reason that the request data was being formatted like this on the front end. Expect to come back later after finding source of difference.

removed methods from game piece model that where known to cause error:
// AttributeError: 'function' object has no attribute 'get'
this was resolved prior to revert and it seems the revert that took place came back further than intended. Methods likely unnecessary in current architecture